export const DEPARTMENT_OPTIONS = [
  { code: "ACCT", label: "Accounting" },
  { code: "AEBI", label: "Biology (Agric & Envir Sc)" },
  { code: "AECH", label: "Chemistry (Agric&EnvirSci)" },
  { code: "AEIS", label: "Indigenous St (Agric&Envir Sc)" },
  { code: "AEMA", label: "Mathematics (Agric&Envir Sci)" },
  { code: "AEPH", label: "Physics (Agric & Envir Sci)" },
  { code: "AERO", label: "Aerospace Engineering" },
  { code: "AFRI", label: "African Studies" },
  { code: "AGEC", label: "Agricultural Economics" },
  { code: "AGRI", label: "Agriculture" },
  { code: "ANAT", label: "Anatomy & Cell Biology" },
  { code: "ANTH", label: "Anthropology" },
  { code: "ARCH", label: "Architecture" },
  { code: "ARTH", label: "Art History" },
  { code: "ATOC", label: "Atmospheric & Oceanic Sciences" },
  { code: "BBME", label: "Biological and Biomedical Engr" },
  { code: "BINF", label: "Bioinformatics" },
  { code: "BIOC", label: "Biochemistry" },
  { code: "BIOL", label: "Biology (Sci)" },
  { code: "BIOS", label: "Biostatistics" },
  { code: "BPHY", label: "Biophysics" },
  { code: "CHEE", label: "Chemical Engineering" },
  { code: "CHEM", label: "Chemistry" },
  { code: "CIVE", label: "Civil Engineering" },
  { code: "CLAS", label: "Classics" },
  { code: "COGS", label: "Cognitive Science" },
  { code: "COMP", label: "Computer Science (Sci)" },
  { code: "COMS", label: "Communication Studies" },
  { code: "ECON", label: "Economics (Arts)" },
  { code: "ECSE", label: "Electrical Engineering" },
  { code: "ENGL", label: "English (Arts)" },
  { code: "ENVR", label: "Environment" },
  { code: "EPSC", label: "Earth & Planetary Sciences" },
  { code: "FINE", label: "Finance" },
  { code: "FREN", label: "French (Arts)" },
  { code: "FRSL", label: "French as a Second Language" },
  { code: "GEOG", label: "Geography" },
  { code: "GERM", label: "German (Arts)" },
  { code: "HGEN", label: "Human Genetics" },
  { code: "HIST", label: "History" },
  { code: "INDG", label: "Indigenous Studies" },
  { code: "INSY", label: "Information Systems" },
  { code: "LING", label: "Linguistics" },
  { code: "MATH", label: "Mathematics & Statistics (Sci)" },
  { code: "MECH", label: "Mechanical Engineering" },
  { code: "MGMT", label: "Management" },
  { code: "MGSC", label: "Management Science" },
  { code: "MIME", label: "Mining & Materials Engineering" },
  { code: "MIMM", label: "Microbiology and Immun (Sci)" },
  { code: "MRKT", label: "Marketing" },
  { code: "NSCI", label: "Neuroscience" },
  { code: "NUTR", label: "Nutrition and Dietetics" },
  { code: "PHAR", label: "Pharmacology and Therapeutics" },
  { code: "PHGY", label: "Physiology" },
  { code: "PHIL", label: "Philosophy" },
  { code: "PHYS", label: "Physics" },
  { code: "POLI", label: "Political Science" },
  { code: "PSYC", label: "Psychology" },
  { code: "RELG", label: "Religious Studies" },
  { code: "SOCI", label: "Sociology (Arts)" },
  { code: "SWRK", label: "Social Work" },
  { code: "URBP", label: "Urban Planning" },
  { code: "WMST", label: "Women's Studies" },
];

const Department_map = Object.fromEntries(
    DEPARTMENT_OPTIONS.map(d=>[d.code,d.label])
)

export function getDepartment(code){
    return code && Department_map[code] ? `${code} - ${Department_map[code]}` : "Code not valid"
}
