CREATE TABLE IF NOT EXISTS bookings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slotID INT NOT NULL,
  userID INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (slotID) REFERENCES slots(id),
  FOREIGN KEY (userID) REFERENCES users(id)
);