-- Sophia Hussain
CREATE TABLE IF NOT EXISTS inviteLinks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ownerID INT NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (ownerID) REFERENCES users(id)
);