CREATE TABLE IF NOT EXISTS slots (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ownerID INT NOT NULL,
    date DATE NOT NULL,
    timeFrom TIME NOT NULL,
    timeTo TIME NOT NULL,
    isActive BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ownerID) REFERENCES users(id)
);