CREATE TABLE IF NOT EXISTS users (
name VARCHAR(100) NOT NULL,
id INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
role ENUM('student', 'owner') NOT NULL,
);